name: pipeline


on:
  workflow_dispatch:
    

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
       - name: Build Deployment Script
         run: echo "Create Change....."

    
  changeApproval:
    name: ServiceNow Change Approval
    needs: build
    runs-on: ubuntu-latest

    steps:     
      - name: ServiceNow Change Approvala
        uses: ServiceNow/servicenow-devops-change@v1.34.2
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNow Change Approvala'
          change-request: '{"setCloseCode":"true","attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment."}}'
          interval: '100'
          timeout: '3600'
    
  deploy:
    name: Deploy
    needs: changeApproval
    runs-on: ubuntu-latest

    steps:     
      - name: Run Deployment Script
        run: echo "Deployment Finished....."
