name: updatechange


on:
  workflow_dispatch:
    

jobs:

 deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:     
      - name: ServiceNow Update Change
        uses: ServiceNow/servicenow-devops-get-change@v2.0.0
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          context-github: ${{ toJSON(github) }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          stage-name: 'ServiceNow Change Approvalw'
          build-number: '6591194141'
          attempt-number: '1'
          pipeline-name: 'Kannyah/test-repo/main'
